# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/huawei/hi6250-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter anne bond dallas figo leland,$(TARGET_DEVICE)),)

endif
